version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
      - run:
          name: L01
          command: cd L01-programmers-tools/hello_world/
      - run: g++ main.cpp
      - run: ./a.out
